theme: jekyll-theme-minimal
title: Психологическая помощь русскоговорящим ит-специалистам
description: Psychotherapy for Russian-speaking IT professionals experiencing stress, fear, borderline states as a result of relocation, job change or dismissal.
domain: ivlev.github.io 
url: https://ivlev.github.io 
baseurl: /ivlev.github.io/   
