theme: jekyll-theme-minimal
layout: default
excerpt_separator: <!--more-->
include:
  - "_img"
title: Психологическая помощь ит-специалистам
description: Профессиональная психотерапия депрессии, стресса, тревоги, паники, вызванных релокацией, сменой работы, увольнением или личными проблемами / Psychotherapy for Russian-speaking IT professionals in a state of depression, experiencing stress, fear, borderline states as a result of relocation, job change or dismissal.
