theme: jekyll-theme-minimal
title: Психологическая помощь ит-специалистам
include: template_github_700.png
description: в состояниях стресса, тревоги, паники, вызванных релокацией, сменой работы, увольнением или личными проблемами / Psychotherapy for Russian-speaking IT professionals experiencing stress, fear, borderline states as a result of relocation, job change or dismissal.
