theme: jekyll-theme-minimal
title: Психологическая помощь ит-специалистам
description: в состояниях **стресса**, **тревоги**, **паники**, вызванных **релокацией**, **сменой работы**, **увольнением** или _личными проблемами_ / Psychotherapy for Russian-speaking IT professionals experiencing stress, fear, borderline states as a result of relocation, job change or dismissal.
